### ISSUE TITLE
Plurally named tag in an h-card explodes the parser

### ISSUE THREAD

**Issue by dpetersen** [indieweb/microformats2-ruby#29]
I've [committed a failing test](https://github.com/G5/microformats2/commit/ad9969e36c358c67ef7b45846b6b7b3b5b143bed), but I really don't know enough about this stuff to propose a solution.  It blows up on [this line](https://github.com/G5/microformats2/blob/master/lib/microformats2/format.rb#L105). Is the markup in the test valid? I got it from [here in g5-hub](https://github.com/G5/g5-hub/blob/master/app/views/locations/show.html.erb#L31).

**Comment by dissolve** [comment]
Because of this issue the current plan is remove the pluralized form in 3.0.0 in favor of `name` to get the entry and `name(:all)` to get the array of all values.

For 2.9.0, preventing the set from happening seems to be the best option.  for h-news you will only be able to get the first entry, but it will at least stop the parser from crashing completely.

**Comment by veganstraightedge** [comment]
This is fixed / changed in `3.0`.
